### ISSUE TITLE
ACT TEST1 and TEST2

### ISSUE THREAD

**Issue by ssabnis** [aerospike/act#38]
In the ACT TEST 1 and TEST 2 you never mentions or provide the number threads/queue. A sample will do. Or the number thread irrelevant for the ACT?

If I am using 56 Core, 256 GB, what would be recommended number of threads.

Also for certification do I need to run "storage" and "index" or just storage will do?

Thanks

**Comment by Alb0t** [comment]
The defaults are in the readme:
```
Fields that you will Rarely or Never Change:
num-queues Total number of transaction queues. Default is number of cores, detected by ACT at runtime.

threads-per-queue Number of threads per transaction queue. If a device is failing and there is a large discrepancy between transaction and device speeds from the ACT test you can try increasing the number of threads. Default is 4 threads/queue.```

**Comment by ssabnis** [comment]
Thanks much @Alb0t ,

Also for certification do I need to run "storage" and "index" or just storage will do?

Thanks again.

**Comment by Alb0t** [comment]
You probably just want storage.

If you are wanting to use all flash/index on disk, that's what that option
is for. If you want to pursue that, you should get in touch with enterprise
support.

**Comment by ssabnis** [comment]
Thanks @Alb0t ,

I do not have enterprise support. We are All Flash shared storage device company. We are not an application company. Please advise how/whom to contact for performance testing license.

Thanks

**Comment by Alb0t** [comment]
I think you misunderstand. You can use Aerospike free with flash storage. ACT testing is free for you use. The index on disk is a special feature that you can use with an enterprise license and only applies on certain scenarios. 
If you want to talk to them about enterprise features, just go here and fill out your details. They're real nice folks.
https://www.aerospike.com/forms/contact-us/

**Comment by ssabnis** [comment]
Thanks @Alb0t , I understand now.

BTW; What is the difference between reads and device-reads sections.? Can you help. Thanks.

        reads                                       device-reads
        %>(ms)                                      %>(ms)
slice        1      8     64    512   4096  32768        1      8     64    512   4096  32768
-----   ------ ------ ------ ------ ------ ------   ------ ------ ------ ------ ------ ------
    1     0.03   0.00   0.00   0.00   0.00   0.00     0.02   0.00   0.00   0.00   0.00   0.00
    2     0.02   0.00   0.00   0.00   0.00   0.00     0.01   0.00   0.00   0.00   0.00   0.00

**Comment by ssabnis** [comment]
@Alb0t .

I get the following error for reads setting 220000.


ERROR: large block writes can't keep up
drive(s) can't keep up - test stopped

How do I interpret this.

Thanks

**Comment by Alb0t** [comment]
exactly what it says. your drive couldn't keep up.

**Comment by ssabnis** [comment]
@Alb0t ,

Thank you. Can you tell me how interpret the following, what is the difference

    reads                                       device-reads
    %>(ms)                                      %>(ms)

Thanks

**Comment by Alb0t** [comment]
I'd suggest moving this discussion to https://discuss.aerospike.com
The readme on the front page goes over this a bit, so other members can chime in too. There isn't as much participation on github.

Have you gone over the README? Specifically, this section with the example..
```The reads table shows read transaction latency (end to end) and the device-reads table at the right shows raw device (small) read latency. ```

**Comment by ssabnis** [comment]
Thanks @Alb0t ,

I missed that section, thanks for the help. I will move the discussion to other thread

**Comment by gooding470** [comment]
@Albot, thanks so much for answering these questions.

BTW, we are aware of the issue where an error line in the log output that interrupts a histogram causes the latency analyzer to do weird things.  At some point we will try to cover this case, since it may not be generally true that an error in the log means the test is meaningless.  I just need to re-learn Python (again) and go back in there...

We also still intend to get to your script to automate testing...

Andy

**Comment by ssabnis** [comment]
Thanks @Alb0t @gooding470 ,

I am capping at 200k/100k r/w setup, after that system behaves. Here are numbers so far into the testing.

![image](https://user-images.githubusercontent.com/1276281/51266813-140e6f80-1971-11e9-918d-b71f3add608f.png)

**Comment by ssabnis** [comment]
Hi @gooding470 ,

What is actually happening in the system for the below error.
```

ERROR: large block writes can't keep up
drive(s) can't keep up - test stopped
```

**Comment by mtendjou** [comment]
Would seem your disk is not keeping up and the write blocks are backing up (not able to be written down to storage fast enough), causing the test to stop.

**Comment by ssabnis** [comment]
Thanks @mtendjou

**Comment by Alb0t** [comment]
@ssabnis are you asking how to create the graph? If you want to change the workload, just edit the config file..
