### ISSUE TITLE
Incorrect values in analysis histogram

### ISSUE THREAD

**Issue by MicahCarrick** [aerospike/act#42]
There appears to be a regression in the analysis script after 2cca4113a273cbcf40c30e94fe2f755e50b8ae77 which results in incorrect latency reported in the first histogram bucket.

**Steps to reproduce:**

1. Run ACT to produce some output to analyze
2. Checkout current commit db9961ff7e0ad2691ddb41fb080561f6a1cdcdc9 
3. Run `/analysis/act_latency.py` and notice large values in first bucket (bug)

```
        reads                  device-reads           /dev/nvme0n1-reads     large-block-writes     large-block-reads
        %>(ms)                 %>(ms)                 %>(ms)                 %>(ms)                 %>(ms)
slice        1      2      4        1      2      4        1      2      4        1      2      4        1      2      4
-----   ------ ------ ------   ------ ------ ------   ------ ------ ------   ------ ------ ------   ------ ------ ------
    1    17.50   0.10   0.00     0.03   0.00   0.00     0.03   0.00   0.00   100.00 100.00 100.00     0.00   0.00   0.00
```

4. Checkout earlier commit 2cca4113a273cbcf40c30e94fe2f755e50b8ae77
5. Run `/analysis/act_latency.py` again and notice correct values in first bucket

```
        reads                  device-reads           /dev/nvme0n1-reads     large-block-writes     large-block-reads
        %>(ms)                 %>(ms)                 %>(ms)                 %>(ms)                 %>(ms)
slice        1      2      4        1      2      4        1      2      4        1      2      4        1      2      4
-----   ------ ------ ------   ------ ------ ------   ------ ------ ------   ------ ------ ------   ------ ------ ------
    1     0.20   0.03   0.01     0.13   0.02   0.01     0.13   0.02   0.01   100.00 100.00 100.00     0.06   0.03   0.01
```

**Comment by kportertx** [comment]
Could you provide the act output that you ran the analysis against?

**Comment by MicahCarrick** [comment]
Hmm, this was based on some testing done on April 4th and I'm no longer able to reproduce (tried with both same version of output and different versions of output).

I'm going to close this out for now and will re-open if I'm able to reproduce using the most recent "finalized" v5.

**Comment by kportertx** [comment]
The output files would have been really helpful. I suspect that the read load wasn't keeping up on the old version which would go unnoticed and give the impression of low latency at the specified read load. The new version multi-threads the read load to hit the user specified target and the benchmark will fail if the target cannot be maintained.
