### ISSUE TITLE
Error reporting is too noisy

### ISSUE THREAD

**Issue by Alb0t** [aerospike/act#46]
I was running ACT tests in a cloud provider over the weekend.. Today I noticed they are out of disk.
```
#:~/act/config# grep -c 'Too many open files' act_250x.conf.out
58379616
#:~/act/config# grep -c '^ERROR' act_250x.conf.out
58433002

-rw-r--r-- 1 root root 3.8G Sep 30 16:36 act_250x.conf.out
```
Okay, I know error logging is important - but this is getting out of hand.

As far as I know, this error isn't helpful. This happens almost every time we push a system to its limits, especially on cloud systems even with us running as root with no file limit set to 1MM. 

```
# ulimit -Hn
1048576
```

This also causes problems with the latency interpreter, making it run very slow and sometimes giving bad results (I've seen it but don't have replication steps for the issue). 

Can we request some changes here? I'm thinking
1) have a flag to ignore open files limit? Or just ignore by default. Is it valuable?
2) Possibly write errors to a separate log file?
3) Could it aggregate errors instead of printing each individual error line?
4) Maybe limit the number of errors reported, like 'repeated 23457x bajillion times' instead of logging each individual problem.

I know the #2/#3 point would make it difficult to troubleshoot ACT so I think just having a flag to ignore this kind of error would be a good thing.

**Comment by volmarl** [comment]
additional info from @Alb0t 

Log lines:

```
ERROR: open device /dev/nvme6n1p3 errno 24 'Too many open files'
ERROR: open device /dev/nvme6n1p2 errno 24 'Too many open files'
ERROR: open device /dev/nvme6n1p2 errno 24 'Too many open files'
ERROR: open device /dev/nvme6n1p3 errno 24 'Too many open files'
ERROR: open device /dev/nvme6n1p1 errno 24 'Too many open files'
```


```
num-devices: 32
service-threads: 2
num-queues: 96
threads-per-queue: 4
test-duration-sec: 86400
report-interval-sec: 1
microsecond-histograms: no
read-reqs-per-sec: 500000
write-reqs-per-sec: 250000
record-bytes: 1536
record-bytes-range-max: 0
large-block-op-kbytes: 128
replication-factor: 1
update-pct: 0
defrag-lwm-pct: 50
disable-odsync: no
commit-to-device: no
commit-min-bytes: 0
tomb-raider: no
tomb-raider-sleep-usec: 0
max-reqs-queued: 1000000
max-lag-sec: 10
scheduler-mode: noop
 
DERIVED CONFIGURATION
record-stored-bytes: 1536 ... 1536
internal-read-reqs-per-sec: 500000
internal-write-reqs-per-sec: 0
read-req-threads: 2
write-req-threads: 0
large-block-reads-per-sec: 5882.35
large-block-writes-per-sec: 5882.35

```

**Comment by kportertx** [comment]
I think we should fail the test immediately when an error occurs in get_fd. The test results are not reliable once this occurs. It wouldn't make sense to 'handle' these errors since we could fail the disk due to a ulimit being too low.

This is the warning you are seeing: https://github.com/aerospike/act/blob/master/src/storage/act_storage.c#L963

Which could be within this call stack: https://github.com/aerospike/act/blob/master/src/storage/act_storage.c#L963

Which is counted as a valid read, which is wrong. As I mentioned above, if he 'handled' the error, we could fail claiming the disk couldn't keep up.

**Comment by Alb0t** [comment]
@kportertx if this is causing an issue and making the test results inaccurate, i'm all for failing the test. I did notice a drop in the rate when using the -x switch on the interpreter. Is there any way we can come up with a formula for how many file handles would be needed? It would be nice if this could be a param in the actconfig and dropped onto the pid at launch time. Maybe even a formula/auto set based on the rate.

**Comment by kportertx** [comment]
The formula for max fds should be:
```
fds = num_devices * 2 + num_queues * threads_per_queue * num_devics

if (tombraider) {
  fds += num_devices
}
```

From this you should only be using about 13K fds max. Even with the 53K other errors which could have closed an fd, we aren't close to 1M.

Are you sure the process is being allowed 1M fds, what is the current softlimit on this machine?

```
ulimit -Sn
```

**Comment by Alb0t** [comment]
```
# ps aux|grep bin/act
root     10068  888  0.0 8096764 26436 pts/1   Sl+  05:59 8331:11 ../target/bin/act_storage act_250x.conf
root     14942  0.0  0.0  14856  1104 pts/0    S+   21:36   0:00 grep --color=auto bin/act

# cat /proc/10068/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             3062796              3062796              processes
Max open files            1024                 1048576              files
Max locked memory         16777216             16777216             bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       3062796              3062796              signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

Is the soft limit the important parameter here?

**Comment by kportertx** [comment]
The hard limit is the max a user can set the soft limit. The soft limit is the actual limit for the process.

Your soft limit is 1024 apparently:

> Max open files            1024

**Comment by Alb0t** [comment]
But this is running as root.

**Comment by kportertx** [comment]
Yes, so root can set the hard-limit, but the root's soft-limit still applies to processes it spawns.

**Comment by Alb0t** [comment]
Confirmed, raising the soft limit seems to help. Didn't expect that. Is it possible for ACT to raise its own soft limit on launch? that would probably be good along with the change you mentioned.

**Comment by kportertx** [comment]
I believe managing system resource limits is a bit outside the scope of ACT :).

**Comment by Alb0t** [comment]
nonsense :) but okay deal

**Comment by gooding470** [comment]
The one system setting we tried to manage was the scheduler, since in the
old days leaving that not set to 'noop' could mysteriously lead to crappy
numbers, and take us long to figure out.  However now we get lots of
complaints about trying to set that from inside ACT (it warns when it
can't), and we will likely take that out.

**Comment by gooding470** [comment]
That said, we need to redo ACT again, given Aerospike server 4.7 and the
removal of transaction queues and threads.  We'll consider all of this
again.
