### ISSUE TITLE
Act_prep and compression

### ISSUE THREAD

**Issue by vbienf** [aerospike/act#60]
Hi all!

I want to run test act_storage with compression 2 (50%). But act_prep clean and then filling my device without compression. How I can run act_prep with compression?

**Comment by realmgic** [comment]
The act_prep is preparation step which is not actually part of the ACT performance test. This step is used to clean up the data from the device or partition (by writing zeroes on every sector of the disk) and then filling it up with random data (salting). This simulates the state of a disk in a normal production environment - where data is "available" all over the disk and none of the cells are dormant or unused.

The actual performance test is done using `act_storage` (and also `act_index`, but not in this case). 

When the `act_storage` run, it writes random data which is not compressible. When you enable the `compression` flag, the objects will be adjusted to have some repeatable data that would make the data compressible. A lower tier compression (like on the disk level) will be able to take advantage of that and you will be able to check for the disk performance, for example. 

Hope that make sense.

**Comment by vbienf** [comment]
So, according to your words @realmgic I can clean my device by myself and fill it, for example, with FIO, before I run act_storage for certification?

You said that "is not actually part of the ACT performance test". But in section from README "Running the ACT Certification Process" I read the words "you must perform the following steps". So, I'm a little bit confusing.

**Comment by vbienf** [comment]
Thanks @realmgic ! Now its clear for me.
